server:
  port: 8082


eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://registry-service:8761/eureka/

okta:
  oauth2:
    issuer: 
    clientId: 
    clientSecret: 

spring:
  datasource:
    url: jdbc:postgresql://medical-record-db:5432/medical-record
    username: medical-record
    password: capstone
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

flyway:
  locations: classpath:db/migration
