server:
  port: 8080


eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://registry-service:8761/eureka/



okta:
  oauth2:
    issuer: 
    clientId: 
    clientSecret: 

spring:
  datasource:
    url: jdbc:postgresql://user-db:5432/user_db
    username: user_service
    password: capstone
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

flyway:
  locations: classpath:db/migration
